modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="jewelcraft"
version="1.6.2"
displayName="Jewelcraft"
credits="Jusey1, Burack"
displayURL="https://discord.gg/s7QaYGUzZU"
logoFile="logo.png"
authors="Jusey1"
description="Craft & enchant your own jewelry..."

[[dependencies.jewelcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.jewelcraft]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

